### ISSUE TITLE
Properties are not always optional

### ISSUE THREAD

**Issue by gvanrossum** [dropbox/stone#130]
Hey Stone team! We found an issue with the typing stub code generated for properties. I believe this block of code should be deleted:
https://github.com/dropbox/stone/blob/e695746e0836dd54d942d6b8a9271d2d3fd8a429/stone/backends/python_type_stubs.py#L369-L371

The effect of this block is to always add `Optional[]` around the return type of a property getter. (The logic looks backwards, but for nullable and void types there *already* is an `Optional[]`.)

But if you look at the runtime code generated, you'll see that for a non-nullable default-less property, `None` is never returned, it raises an exception if the value isn't set:
https://github.com/dropbox/stone/blob/e695746e0836dd54d942d6b8a9271d2d3fd8a429/stone/backends/python_types.py#L625-L634

I will propose a PR to fix this. I have tested the PR in the Dropbox server repo, and it caused only two errors, and those look genuine.

CC: @ilevkivskyi

**Comment by starforever** [comment]
nit: should the second code example from line 609 to line 618?

**Comment by gvanrossum** [comment]
Oh, you're right. Here's the code fragment I meant to link to:
https://github.com/dropbox/stone/blob/e695746e0836dd54d942d6b8a9271d2d3fd8a429/stone/backends/python_types.py#L603-L618
