### ISSUE TITLE
Pypi

### ISSUE THREAD

**Issue by TommyPujol06** [dropbox/stone#132]
In the pypi page [here](https://pypi.org/project/stone/). It looks like there has to be some docs. but they aren't.
~~~~~~~~~~~~~~~~~~~~~~~
*Introduction
    * Motivation
    * Installation
* Language Reference
* Builtin Generators
* Managing Specs
* Evolving a Spec
* Writing a Generator
* JSON Serializer
* Network Protocol
~~~~~~~~~~~~~~~~~~~~~~~
But all results whith the 404 page at pypi.

**Comment by heterosfer** [comment]
If you look at the [README.md](https://github.com/dropbox/stone/blob/master/README.rst)  page, you can find the documents. (Pypi document cloned by it self.)

**Comment by TommyPujol06** [comment]
@heterosfer Ok, but anyway there should be a link to that on pypi.
It isn't a priority to do so, but it would be great.

**Comment by greg-db** [comment]
Thanks for letting us know! I'll ask the team to fix that up.

**Comment by TommyPujol06** [comment]
Ok

**Comment by connorworley** [comment]
These appear to link to Github now.
