### ISSUE TITLE
Does Boolean data type interpret integer values?

### ISSUE THREAD

**Issue by demberto** [dropbox/stone#156]
I have a parameter coming from server which is logically a boolean but not in the form of `true` or `false`. 1 means `true` and 0 means `false`. Can I do something like: `true_or_false_in_int Boolean = 1`? Since I care about only having a Python backend where assigning 0 or 1 to `bool` yields `False` or `True`

**Comment by greg-db** [comment]
No, the validation won't allow you to supply an int value to a Boolean field. 

I'd recommend having the server return a real Boolean, or if that's not possible, you might instead want to do something like `true_or_false_in_int UInt32(min_value=0, max_value=1) = 1`.
