### ISSUE TITLE
Which OSs are supported?

### ISSUE THREAD

**Issue by BastianZim** [dropbox/stone#214]
**Before you start**
Have you checked StackOverflow, previous issues, and Dropbox Developer Forums for help?

Yes

**What is your question?**
A clear and concise description of the question.

I'm currently in the process of updating the dropbox-sdk-python on [conda-forge](https://conda-forge.org) which seems to require stone: https://github.com/dropbox/dropbox-sdk-python/blob/250b116f77b8f22351c1e2e0eb625d0d19f86f2c/setup.py#L30 

I, therefore, wanted to bring stone to conda-forge as well, but the tests fail for windows, as can be seen in the logs here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=277449&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=23010c01-6a9d-5f94-9037-792618644b77

From a cursory overview, I can also see that you're not testing on windows (Although I just quickly checked that, not sure if you're testing windows differently?):
https://github.com/dropbox/stone/blob/314d2972ce92dd381b2f6cd7e7610e128fd0069a/.github/workflows/CI.yaml#L11-L17

Is it correct then, that stone is only available on macOS and Linux, or am I missing something (Which I would assume since the python client, which depends on stone, is)?

**Screenshots**
If applicable, add screenshots to help explain your question.

**Versions**
* What version of Stone are you using? _3.2.1_
* What version of the language are you using?
* What platform are you using? (if applicable) _Azure DevOps Pipelines Windows_

**Additional context**
Add any other context about the question here.

The PR is here: https://github.com/conda-forge/staged-recipes/pull/13960

Edit: The test logs also suggest only macOS, from what I could find: https://github.com/dropbox/stone/actions/runs/514261108

**Comment by greg-db** [comment]
Thanks for writing this up! It looks like we don't have official documentation on platform support for this, so I'll raise this with the team to see if we can get some official guidance for this.

**Comment by BastianZim** [comment]
Thank you!

**Comment by BastianZim** [comment]
@greg-db Just to add, could maybe someone from here also have a look at the logs? Maybe the error is not related to windows at all? I've been trying to investigate this but haven't found the reason yet.

**Comment by greg-db** [comment]
@BastianZim Thanks for the note. I'll ask the team to review that when they can.

**Comment by BastianZim** [comment]
Thank you!

**Comment by BastianZim** [comment]
Hi @greg-db just want to check if there's an update here, as this has quite a substantial impact so any news would already be helpful?

Thanks!

**Comment by greg-db** [comment]
This is still open with the team, but I don't have an update on it yet unfortunately.

**Comment by BastianZim** [comment]
Hi @greg-db, just wanted to check in and ask if there are any new developments here?

**Comment by BastianZim** [comment]
Ok thanks for the update. Does that mean then that the dropbox python client is also intended to not be available on windows, since it depends on stone?

**Comment by greg-db** [comment]
@BastianZim No, the Python client works on Windows. It's generated using stone, but it runs on Windows. You don't need to set up a stone development environment or know about stone to use the Dropbox Python client.

**Comment by greg-db** [comment]
It does have a dependency on stone, but the Dropbox Python SDK does install (e.g., via pip) and run successfully on Windows. I was referring to how the tests for stone aren't configured to run on Windows as you mentioned.

Anyway, this is open with the team to look into properly. I'll let you know when I have an update on that.

**Comment by rogebrd** [comment]
It looks like in the current state, stone is not functional on it's own in Windows. I have a pull request open to update the supported versions in the CI pipeline which will include ubuntu, mac for python versions 3.6+

**Comment by BastianZim** [comment]
Thanks for the clarification @rogebrd. That would then mean that the dropbox client is also not available, correct? @greg-db had mentioned that the part of stone that the dropbox client relies on works on windows but I don't see a way to make only that part of stone available on windows and restrict the rest of stone to unix, as long as it's in the same package.

**Comment by rogebrd** [comment]
I see, I guess that would be the case, I can take a look at making windows supported for stone so we can make sure the python sdk can properly use all the dependencies. For clarification, the sdk should work correctly on windows, we just are unable to properly run all the tests in the windows environment

**Comment by BastianZim** [comment]
Awesome, thanks!

**Comment by BastianZim** [comment]
Hi @rogebrd is there an update here?
