### ISSUE TITLE
Do tests require pytest <5 or <7?

### ISSUE THREAD

**Issue by BastianZim** [dropbox/stone#215]
**Before you start**
Have you checked StackOverflow, previous issues, and Dropbox Developer Forums for help?
Yes

**What is your question?**
A clear and concise description the question.

setup.py lists pytest at `<5`: 
https://github.com/dropbox/stone/blob/314d2972ce92dd381b2f6cd7e7610e128fd0069a/setup.py#L26-L28 
Whereas test/requirements.txt lists it at `<7`:
https://github.com/dropbox/stone/blob/314d2972ce92dd381b2f6cd7e7610e128fd0069a/test/requirements.txt#L3 
(Introduced in #191)

Just wanted to check which one's correct?

**Comment by greg-db** [comment]
Thanks for raising this! I'll ask the team to check and fix this.

**Comment by BastianZim** [comment]
Thank you!
