### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by samschott** [dropbox/stone#288]
**Describe the bug**
Stone's frontend uses the `inspect.getargspec` method which was deprecated in Python 3.0 and removed in 3.11 (see https://docs.python.org/3.10/library/inspect.html#inspect.getargspec).

https://github.com/dropbox/stone/blob/bdd49bc1017dcea2d193beb1925cded33a276d54/stone/frontend/ir_generator.py#L1077

This results in attribute errors when running stone in Python 3.11.

**Versions**
* What version of the Stone are you using?  3.3.1
* What version of the language are you using? Python 3.11
* What platform are you using? macOS 13

**Additional context**
The recommended migration path is to use `inspect.getfullargspec` as drop-in replacement.

**Comment by greg-db** [comment]
Thanks for the report! I'll ask the team to update that.

**Comment by fabaff** [comment]
For a lot of distributions will `stone` fail to build due to the missing support for Python 3.11. This will lead to broken `dropbox-sdk-python` packages down the road.

**Comment by greg-db** [comment]
@fabaff Thanks for the note!

**Comment by dvzrv** [comment]
Hi! We're currently rebuilding all Python packages against Python 3.11 on Arch Linux. This project is now broken.

Can you please replace the use of `getargspec()` with `getfullargspec()` (see https://docs.python.org/3/whatsnew/3.11.html) and release a new version? Thanks! :)

**Comment by greg-db** [comment]
@dvzrv Thanks for the feedback! This is open with the team. I'll follow up here with any updates.

**Comment by johnlarkin1** [comment]
Hey @samschott @dvzrv - genuinely apologize for the delay here. I did not realize that this was an issue until today (when I came across it myself). I have pushed up PR#299 which will address this. 

I'm working on getting this merged in today! Thank you all for your patience and thanks for pushing up an issue 👍 

https://github.com/dropbox/stone/pull/299

**Comment by wfraser** [comment]
fixed in https://github.com/dropbox/stone/pull/299
