### ISSUE TITLE
Stone should generate `#type` declarations for generated Python code

### ISSUE THREAD

**Issue by posita** [dropbox/stone#45]
Currently, when targeting Python, Stone does not add `#type` declarations to generated code. I don't know how difficult this would be, but it probably should.

**Comment by wittekm** [comment]
Hi! Stone does this, actually, using PEP 484 .pyi files - they are separate files that define the types, but otherwise behave exactly like `# type:` annotations.

Try out the `python_type_stubs` generator.

Example: https://github.com/dropbox/stone/blob/master/test/test_python_type_stubs.py

**Comment by risforrob** [comment]
Closed per @wittekm
